sudo: required
services:
  - docker

before_install:
  - docker build -t oscartematio/docker-react -f Dockerfile.dev .

script:
  #Build docker_image
  - docker build -t oscartematio/site_cv ./
  - docker run oscartematio/site_cv -p 500:5000
  #logging to the docker repository
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin 
  #pushing image to dockerhub
  - docker push oscartematio/site_cv
   

deploy: 
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "cv-oscar-miguel"
  env: "CvOscarMiguel-env-1" 
  bucket_name: "elasticbeanstalk-eu-west-3-920198304117"
  bucket_path: "cv-oscar-miguel"
  on:
    branch: master
  access_key_id: 
    secure: $ACCESS_KEY_ID
  secret_access_key:
    secure: "$SECRET_ACCESS_KEY"