FROM python:latest
RUN apt-get update -y
RUN apt-get install -y python3-pip python-dev build-essential
COPY . /app
WORKDIR /app
RUN pip3 install -r  Docker/requirements.txt
ENTRYPOINT ["python3"]
CMD ["app.py"]